# action.yml
name: Github action - Autodoc
description: |
  Update readme with workflow and action docs.
inputs:
  workflow_file:
    description: |
      Path to the workflow or action file to document
      example workflow: `.github/workflows/plan.yaml`
      example action: `action.yaml`
    required: true
    default: ".github/workflows/plan.yaml"
  doc_file:
    description: |
      Path to the markdown file to update with documentation
      example: README.md
    required: true
    default: "README.md"
  start_token:
    description: |
      Token marking the start of the autodoc section
      default value: <!-- autodoc start -->
    required: false
    default: "<!-- autodoc start -->"
  end_token:
    description: "Token marking the end of the autodoc section"
    required: false
    default: "<!-- autodoc end -->"
  table:
    description: "Format inputs as a markdown table"
    required: false
    default: "true"
  debug:
    description: "Print debug messages. 0=none, 1=some, 2=more, 3=all"
    required: false
    default: "0"

outputs:
  file_type:
    description: "The type automaticly detected by the script of the input_file documented: workflow or action"
  autodoc_out:
    description: "If enabled, the generated documentation for inputs, secrets, and outputs"

runs:
  using: "docker"
  image: "docker://ghcr.io/nrkno/github-action-action-workflow-autodoc:v2.0.3"
