# action.yml
name: "autodoc"
description: |
  Update readme with workflow and action docs.
inputs:
  workflow_file:
    description: "Path to the workflow file to document"
    required: true
    default: ".github/workflows/plan.yaml"
  doc_file:
    description: "Path to the markdown file to update with documentation"
    required: true
    default: "README.md"
  start_token:
    description: "Token marking the start of the autodoc section"
    required: false
    default: "<!-- autodoc start -->"
  end_token:
    description: "Token marking the end of the autodoc section"
    required: false
    default: "<!-- autodoc end -->"
  commit_message:
    description: "Commit message to use when committing changes"
    required: false
  author:
    description: "Author name to use for git commits"
    required: false
  author_email:
    description: "Author email to use for git commits"
    required: false
  debug:
    description: "Print debug messages. 0=none, 1=some, 2=more, 3=all"
    required: false
    default: "0"
  skip_commit:
    description: "Skip git add/commit/push and only update the doc file"
    required: false
    default: "false"

runs:
  using: "docker"
  image: "docker://ghcr.io/nrkno/github-action-action-workflow-autodoc:v1.3.3"
