on:
  pull_request:
  workflow_dispatch:

jobs:
  autodoc:
    name: Auto-generate Action Workflow Documentation
    runs-on: ["nrk-azure-intern", "linux"]
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Auto-generate Action Workflow Documentation
        uses: nrkno/github-action-action-workflow-autodoc@v1
        with:
          workflow_file: action.yaml
          doc_file: README.md
