on:
  pull_request:

jobs:
  commitlint:
    uses: nrkno/github-workflow-semantic-release/.github/workflows/workflow.yaml@2a544544e6e6dda63243f5c75d88bbc2b0368402 # v5.1.4
    with:
      runs-on: ubuntu-latest
      release-enabled: false
