on:
  pull_request:

jobs:
  commitlint:
    uses: nrkno/github-workflow-semantic-release/.github/workflows/workflow.yaml@6a8585e39eabcb53cdbdebfcc76eb9672199089e # v5.1.5
    with:
      runs-on: ubuntu-latest
      release-enabled: false
