on:
  pull_request:

jobs:
  commitlint:
    uses: nrkno/github-workflow-semantic-release/.github/workflows/workflow.yaml@08fcf668fb855fad47569391a4bea4f36dfc0292 # v4
    with:
      runs-on: ubuntu-latest
      release-enabled: false
